### ISSUE TITLE
problem with building dictionary

### ISSUE THREAD

**Issue by redguy666** [morfologik/polimorfologik#1]
Hi,
I tried to build dictionary following provided information (dowloaded all external dictionary files, etc), but the result is always different from provided polish dictionary and does not work with solr. Also - when I tried to use fsa scripts with default pl.dict from standard jar - I get errors:
# >fsa_guess -d pl.dict

Invalid dictionary version in file: pl.dict
Version number is -58 which indicates dictionary was build:
with yet unknown compile options (upgrade your software)

**Comment by janchorowski** [comment]
Hi,

sourceforge stopped hosting the morfologik files, where can the polimorfologik.txt be downloaded from right now?

**Comment by dweiss** [comment]
Please do not attach comments unrelated to the issue. I've created a new one for you, here:
https://github.com/morfologik/morfologik-scripts/issues/3
