### ISSUE TITLE
pronoun 'on' is marked as a form of 'nie'

### ISSUE THREAD

**Issue by rafalkrupinski** [morfologik/polimorfologik#20]
on;nie;ppron3:pl:acc:m2.m3.f.n1.n2.p2.p3:ter:akc.nakc:praep+ppron3:sg:acc:n1.n2:ter:akc.nakc:praep

is this correct?

**Comment by milekpl** [comment]
Yes.  This is a plural unaccented form: 'chodziło o nie'.
