### ISSUE TITLE
Vocative of village name "Bystra" should be "Bystro"

### ISSUE THREAD

**Issue by mikolajz** [morfologik/polimorfologik#4]
The lexicon contains both a lower-case common adjective whose vocative is correctly "bystra", but also an uppercase words which can be the village name and should IMHO have the vocative "Bystro".

**Comment by milekpl** [comment]
Well, according to the linguistic norm, the vocative case should be equal for nominative for adjective-based substantives (for example, "Kowalska"). Unless you have some evidence that this is actually the usage in the village itself, it must stay as is.
