### ISSUE TITLE
"Portland" and "Bradford" are inflected even if that's not the common practice

### ISSUE THREAD

**Issue by mikolajz** [morfologik/polimorfologik#5]
When searching in Google:
"w Portlandzie" -> 963 hits
"w Portland" -> 243 000 hits
Morfologik:
Portlandzie	Portland	subst:sg:loc:m3+subst:sg:voc:m3

"w Bradfordzie" -> 1070 hits
"w Bradford" -> 325 000 hits
Morfologik:
Bradfordzie	Bradford	subst:sg:loc:m3+subst:sg:voc:m3

**Comment by milekpl** [comment]
Indeed, Portland is even marked up as "ndm" in Słownik poprawnej polszczyzny. Will fix in the next release.
