### ISSUE TITLE
Numeral tags ambiguity

### ISSUE THREAD

**Issue by wwrobell** [morfologik/polimorfologik#9]
example:
```input ->10,"inst","f"    (dziesięć, narzędnik [z kim? z czym?], r.żeński)```
```output->"dziesięciu"                         //it should be "dziesięcioma"```

PoliMorf:

Odmiana | F. Podstawowa | Tags
--- | --- | ---
dziesięciu | dziesięć | num:pl:gen.dat.inst.loc:m1.m2.m3.f.n2:congr
dziesięcioma | dziesięć | num:pl:inst:m1.m2.m3.f.n2:congr

All of above fit to tags, but first seems to be incorrect.

**Comment by milekpl** [comment]
Both are correct:

http://sgjp.pl/leksemy/#90109/dziesięć
